import { registerSW } from 'virtual:pwa-register'

// Registers the service worker generated by vite-plugin-pwa.
// The app shell can be installed and updated automatically after production builds.
registerSW({
  immediate: true,
})
